### ISSUE TITLE
Where could I get the database 

### ISSUE THREAD

**Issue by YoungForever222** [eMapR/stem#1]
Dear Sir,
I am a student from University of Science and Technology of China. I'm very interested in the model of STEM, and I want to use it in my work of protecting a kind of rare bird. I think STEM will help us a lot. 
After a basic test of the code, I think that I need a group of database to make it work. Could you please help me with that database, or some instruction of the form of the data.
Thanks you very much!
Yang

**Comment by smHooper** [comment]
The STEM code we have is sort of oriented toward our particular system, but we have tried to make it generalizable too. It shouldn't really require any special data format other than predictors (i.e., features for decision trees) in [a format readable by GDAL](http://www.gdal.org/formats_list.html). However, the format of the parameter text files are sort of particular, and that might be the cause of the problem.

Where exactly is the code getting stuck? Could you send me the error that your getting, the script the error is from, and the line number?

Also, depending on the bird observation data you're using, you might want to consider [AdaSTEM](http://www.cs.cornell.edu/%7Edamoulas/Site/AdaSTEM.html), a variant developed by the lab that developed the original STEM algorithm. This is particularly true if your observations are unevenly spatially distributed like those from eBird. The main difference between STEM and AdaSTEM is that AdaSTEM determines the size of each support set by the density of training observations.
